secrets:
    sops:
        age_key: ENC[AES256_GCM,data:CAg+M+oFyfbVkvGcPN8Mn/YtuXdQrtf6wmtNsgzMbxQo9QkkWUvFrMO+ceAna3HTofE+NKlYuiNOJGxDBuhpSmIuyHKX1VRE/n4DlX68ISq8bW3L//RQBnxHQ8TqhXGA21+TiNdoDnACK5FKG3R39m/UibtRDkvDYx2LZ2hnYaeILFmihU/091lgYuKAJYUZ1eBF6maYnS7IK1GdVVZbbMR+ZrpkHEiXjPZlIYi1Wc0ZqNW84H1l,iv:bQKml1OG+lfgf1luipSlao+40dRyb2r2pdnAx/l/Yss=,tag:s1YJtmSqN+oiNQSCknacNA==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:GwM3Y8tH1ay8CFsd+1cIgsjrCoITgVZVcoUOUde32Yo9Hkip/j1mkvVGCjc=,iv:dsL0szz6vWcdVd9Wbzqadqut0zQfCdKFlS7tvbASmW4=,tag:omTUbjQNbHSTGXP5jA0qCA==,type:str]
            username: ENC[AES256_GCM,data:uRiNspE=,iv:PHIinoP3Ws+FQzTM013TAd+U4ToQ1eiObDoTCvnKGfw=,tag:8RnqlM7mpyqBh3rVGZx+yA==,type:str]
            password: ENC[AES256_GCM,data:CelmuIBD0oPCZ04=,iv:YmxRsOpggZMI4+eS6+vVMlw7Mq8cxHpXrt1MU9Ab3CM=,tag:j82bSaU4xe9QBbfTYKTmmw==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:YSip9sWcbg==,iv:UVGHg8Angq8MPzh2l0NhlLmPcVO4ZB5ES1cw2WDkJXo=,tag:DBeI+txvuGccOZiD9HgLcw==,type:str]
                password: ENC[AES256_GCM,data:MSywnr2g2QrGaFVrYRVA7o+qDogkN8ydUQW3XrXbN8g0OOgwf4TxFg==,iv:dU7gKDFj2ZaZCFt8QXRF+SLmLxtFBSbEOA9OquN7E68=,tag:dBp8OXn0lX9hl+jt8NELNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q5cu4mlasj5nuyfyckyr2v8vhnuw3nlaav4k7t5qem352yxcv32s6vlvyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OFZRb3JNZUJjaGJKZk9L
            SUtDRWF5d0xyeWtBbUx4VlJXTmpqYVJLdFJvClNjTElVTUtQcUtrZVhlWWowdElr
            UGhjdnltWTBGQ3NyUGNpbHhMcTNianMKLS0tIGMrV2IvcVJva3hLM3NTWWFhMjYy
            emJCdlB0VXN1SWdRNFlyYlFQdE15eEUKamZCtXhlwEM+HFVv2nTCeBkHhCIl3Qzf
            7fH01hmOrYDzuNFGB75wPF/Oj5qJJ56rB+2cH5UEpTwxgDqcBaVpbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T10:05:42Z"
    mac: ENC[AES256_GCM,data:cnrAXjxIVH1ttnQ6LtW4ZqkxC/OrMW0Ddj82JgkueE5CpwRXCMXN9nYnAy2j9f5GnrpqZSDUCXevLLMAPc6I+c382pDpIrg9Wmvcw8d5WYuSl2YZxnjIu59PrUivmusdojoH9ryIRL3kw8LR9PcVZhHUrhUuXY1PCp7EiWnf9EM=,iv:CNvx3RJF5j4+7JQyWunheDRqBtYF2Qy8qBJx1/dMLCc=,tag:K57j+pbyRsXjI3x76N8ffg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
