tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:gglQEzewcwcliEPAqGB5UbnG0x+y437/xwgYB7Lc6hg/,iv:QBCT/eGxODsvYLeWgYQEhAeHYyMuzH8ejZmjpCwVU9M=,tag:63+O5s2875MLafKoBcpuLA==,type:str]
                username: ENC[AES256_GCM,data:N9/XUh0=,iv:sn29Oh5R/Go4BYN8Kp7peACIlrhqL0Bi0FDVX0inKPc=,tag:s6GFukOXpTSMLEYe7Ubo3A==,type:str]
                password: ENC[AES256_GCM,data:dBrcaTlIv4fHjGo=,iv:Ctb/KF8f9Gp4rp/HbaVQFkMTjWIr7U2L+7Nk/pdSjag=,tag:4Rlerg7KnB/eosjTdoS4TQ==,type:str]
        tap_gui:
            app_config:
                auth:
                    allowGuestAccess: ENC[AES256_GCM,data:A9ja/w==,iv:LIiFka2y11yYqvg94ooMvL5toCTAxh5wTBbGxX02u1Q=,tag:amAawRbiKJe2ghQJ/+lMOQ==,type:bool]
                    environment: ENC[AES256_GCM,data:pg4kP/z+EVeKV98=,iv:Pngtoyw2bRregK3fq2OX7Hg8nKk+imUV8+H4uxS2qYw=,tag:nna9GPXuus/UqZ+dEdIFjw==,type:str]
                    providers:
                        github:
                            development:
                                clientId: ENC[AES256_GCM,data:foDj9O2yIWSdjVkIdyW8fGVQXE0=,iv:21Hru76iolKh9R7Vm+iJj0iEEgSFttG7ChIpZshx+KI=,tag:OwiG62dq0b2krsBiV/l5aQ==,type:str]
                                clientSecret: ENC[AES256_GCM,data:AqZuMX5rI0iAp5qohehYi4CVNVGn3keHwRxUe/0xC4ITJ0xBgYQxYg==,iv:LA8vfq4dF9NtgwHzatenoBZI6ZmpCkhjeE8ZDO0xUcs=,tag:03ICZYL+GEM01iTbll9D3w==,type:str]
                integrations:
                    github:
                        - host: ENC[AES256_GCM,data:gClMbXdAXn+23A==,iv:/WVNIe+YSYDgYL/YcMlkcUb6Bmv0WkyJA/0w2jU8VyE=,tag:3Pq8oRYhlE8OjNl/LlU+ZA==,type:str]
                          token: ENC[AES256_GCM,data:TrHUdkuV1qCXlFMxurGiHTBoWiV+slqV5Q6RMb1d3N16PL5lYLTkdw==,iv:0dqOU+ySSwNWnU1APE8kwdnZC1NHlrKgMt7FIZEzTo8=,tag:745Enc3QX6n0EMd67OrTSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgfw7y6cwv6rxwcse2ksfheg2r8q26htqf7eh75ecs70njdna56s8rn4vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RnBKc0ZZRDRUQng2TFp6
            Z3BGcGxGTDdqelh2c3h5ZDhxV3M3RzJpanpFCjRnbjNjaDFIOHZsa3dNQzY1SjNk
            NGZWQy9xOUozOVVTUDJDS1o2TE5hVDgKLS0tIFZsd3FqSlBtMFlPNlFxSGJ0bUdC
            UE9QUGtuRXRZd05wZnBNRXhRVC91bUUK5FjiKteqNPZIlGEq7rNnLfvuLTBSFeJj
            XGOT1rPxl9o8sM/0Uvr4QHPvMdUTzulrf6N6kTKw41AYi0r4+bMJpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T10:24:13Z"
    mac: ENC[AES256_GCM,data:p4T5pkG8YrzPjjWXorHDGD7IaqaEjVcRpX2D/rdzcoaBMcDlRToHJTdxK1HDHXnTzAGWJsn6vI6rejiYSSmBlmETbIp6tKW/BJZ+r3AuNes9RZwJBagxpz9tQcbw4RjkV/3/rWnCkjlzYrWP97cwZ4FHCV3jPXzayP90N/+iUPU=,iv:WElZ1thUWhZlQdAIimBfo9ORHht9nuzaSOFDwNs872U=,tag:0iRjo7mjzSDjXV8QoZRcmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
