apiVersion: ENC[AES256_GCM,data:gn4=,iv:azv65+SvY08aFGbRsFBiAP3aCOi1evS0sXu8lBoEQmk=,tag:FPLYAqaAvGyBBIPpl7aLaQ==,type:str]
kind: ENC[AES256_GCM,data:jjW+1q96,iv:Br+ED/WA0jOk1g/ikKWv7nTqQN+os5lFNeOWl5Nb/8E=,tag:rmpL+hfoAIfM6jBBlv4XEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lknJE13TIzirbrenxOtd+w==,iv:6VMHg22m/PTdHaX1LAskZvQDv+yWHhDN+clmywA5ut8=,tag:x4zt+ybDm3IMK1ejguwvjw==,type:str]
    namespace: ENC[AES256_GCM,data:DY66IsaY6p27brU=,iv:wr7NpPJeCcMyiak7QltnqdrRWgsrpkcJJARW3SBMxMA=,tag:XIdq99Og3RpgcCMqEuyO2g==,type:str]
type: ENC[AES256_GCM,data:8dGcBYwgMlEBXHQpI2/ovCLZdbOGlvcx,iv:rluZso2O/mqP/8+TAoxH+xrQDxGhWD087OyLbWn6v6A=,tag:KZA+zK+J//GQ3+rerzdITw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:eM0TwIJ4UQ==,iv:2GZ1AbsF2NCF+TNeif+JzTeyHX0ZMv3Aa7psbHYXS94=,tag:vOyyJfPbnqOq2Hq9o13jHg==,type:str]
    password: ENC[AES256_GCM,data:jFq2vXW53JNb+n5YE7InmteEtg6H/jXGd0QoTxMHSvF/ggQ3jXFD0w==,iv:4gNtR5yUgfXYzqmiyyJ84QQ7/J+o1QqWz94dW7Xm1is=,tag:YWMN3W6dPlP6HytBWu2buQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgfw7y6cwv6rxwcse2ksfheg2r8q26htqf7eh75ecs70njdna56s8rn4vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Snl6QW1LMStGd3diUnlM
            YWYxTGV3WFpYOWZIeWNpRkYvWGJveUlFdmhzCmw2ZVlLVldEMUxiN2E4VFpGSkpH
            WnM5VlV4SmoxeWY3RDFmZ0NzZ3ZrOWcKLS0tIGhZQTlLaUNuUmdnUENhcE1yaDFy
            d0xKVU1GcnZ3Z214VWU5MXlCZnA2UkEKAfyLZ9FGYUn6uuGZthWDizT/OTd6zx4b
            Gp1aN4mTUEfhBrFsjKatkjpb/p8ueURztYCYtYkLd9Xtq61Q4cB05w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T10:24:13Z"
    mac: ENC[AES256_GCM,data:a/GY+AnQ1xjzHJEln3V5stp9e2l4CbhaJqK23c2n5MRH5iXkh2Wjj7vup7hnjiwEkH8s62xXCmPJHDzC5qwPR12l0/P6C2vKoHjx5tONPi20eD80JCOkNi45E2miTGNHqIHJ+mJS7jwsOVUYgd8BBm3jFGG6K3lERkDFruKJl2E=,iv:0WaNIkGWaJsfKbQqLNOvtlr32uvY+jwEgpZJefYdM4Y=,tag:FZrOBSR+Pth9XYvkPE8CzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
