apiVersion: ENC[AES256_GCM,data:klQ=,iv:E3cdjpMhXTkUzrXY2P33sOpTwvT3OnNoq5KyxyJyTFQ=,tag:qeL2RvP7Xr18wnR19hRgPg==,type:str]
kind: ENC[AES256_GCM,data:1ZcCqKxN,iv:HAkOUT12hFsPS4fJLhRF6RGg1Vs/pq2sjENWu8qxkII=,tag:qpognCpFfzYciv3QD52W9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9DyLurOuYzuXZ+rRh3w=,iv:FLsTHlifZEPH9vczwWq98mbeqVHsmj1C9oEl2DQD+S0=,tag:eKkIiYVDo/wQONuIUi9LIQ==,type:str]
    namespace: ENC[AES256_GCM,data:lEZX9waEIznJl5E=,iv:wwK9I2M/VmvaEWoSW35eKf4dohF23VyvFOycbKyyf5c=,tag:4C1Tou9yS+zen7j2fNaWLg==,type:str]
type: ENC[AES256_GCM,data:1dwa0J1KBgrj+jxlYuPU2yLI2fUpIweX6it8tK7s,iv:7M2vwQJkl63SDK64iffO+NediXjZWoZrVhJHZeHtVfw=,tag:Nvh+nMgdXBx9F0kV0WR/fA==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:r7HhN4nM0sKk7O2jp/Ti33mD0pWuAao4/RZIhwHoL0dIylQssa07qBZGg2KLipbRxpER88zXvr1+LZ2GZMMWrV6fSjOPvQtq+ackddPbMjIly0MZX059HJ9hW5aTwnMKYAwlWcZCIV59lGA8NIffHp6bTl0JTladugCuNuMeQ+0mLCUP363qy6uMvFCeA/mQKy63uBqpVpG+L+MP6KPBkJqiQ0NFFEqD,iv:jxFhqzU6kQYAlXUzqJP+MQRtzHH7JhJ63CPtxTeuGo0=,tag:ft9dHRNXdhNBjd6dkyR7/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgfw7y6cwv6rxwcse2ksfheg2r8q26htqf7eh75ecs70njdna56s8rn4vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU1NNekFhajNxaTQvVjBT
            dTJ3L205c1Y5Nk5QSGFHeW5SUCtTblhSYVZ3Ck50RmFZME5zNXY2M3ptak9mb1hq
            aExPOTlLRnhHM3I0Z1FSdFJqL2pNaUkKLS0tIExicEZteHMrWk5GRDhlem9hUzln
            SGp1a1hEMTc1ajNrMDNkTXZhcmZxVU0KhLFqy29m7DDoC0AjeYCpL6kh3lpKNaOX
            UlHay5RfW1ocN2mwZKvRRtvgDaLTIWnNqkA7O+gUSp/epNO+5RIbdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T10:24:13Z"
    mac: ENC[AES256_GCM,data:uwYY/jcM+gkmaCJrOZiDqHNvRnKn930QVy42nAiU4hmddHDat4DX7xVTahcd1b3SfzKIqZDZOINWXyAfnlncZiGCX/EYMDXCe93S5BO4RVCwvk8sqq5hl9C+iLKqCZYXzb7xXtAC21vkisboFVS1dPHH4QLncGmZ0rjF9op4qM8=,iv:ZWxZP28l7dGpdPF4dS2v6DfLpgMpZvum6bx1ntE6Z/Y=,tag:owrj7xplVpaMbSWkIIRV1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
