apiVersion: ENC[AES256_GCM,data:6Wo=,iv:MnjkIZ5vuBSiKU0UsKg3hLvwY/LbJpRK9VVoFjjzLek=,tag:WJyQSIoOqEnIK62dTbUEkg==,type:str]
kind: ENC[AES256_GCM,data:BqLpOBvI,iv:Ktvx1wW8O2dWmjuL0jQUz6q2ur4z5iMyiPQCsQTO2as=,tag:h0pqLDgI0AIImXQ59dk0Ag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xzTEapnjgmHAbMsmsiXa1Zw=,iv:B9TDgJXFQlCDwbQjgq1TR56aPlV4Ib5YCpqZ9v3KY8k=,tag:GnmVMBqHexO/tsmZCxDp7Q==,type:str]
    namespace: ENC[AES256_GCM,data:vzHF7NSZWSRvdwc=,iv:dbcPajqcFean2S/wm1xJycok3gfINz2mxjJNb7uxbOQ=,tag:tm4FlWPuMos1vA/2iwDzLQ==,type:str]
type: ENC[AES256_GCM,data:JumNzolSlx16EOPKK8DXbzcu3gTAtASy,iv:ZpUsPQvbI+jh/6JnyMffYbbY2MGySHEexa3N9i7ns3E=,tag:molLL/39KXmNj97zf8A1iA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:G8ZWbQoGZQ==,iv:WSivnrW7HUcrb5nSzLVwoitrc2gB6M52V32QmddnULA=,tag:V4SRO1A7dBTrEHjB7F+EuQ==,type:str]
    password: ENC[AES256_GCM,data:BjmBPvz55MJQJsa2rDkdzxaWG9h9rJyFk+iF87Y5+0udgFQi1L351w==,iv:OWOt3kaXApVNfXYpID+dzKIG2bbtJ/4KaMMy+E18JdY=,tag:K1Q4248pWYU8mXzZWVWoxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgfw7y6cwv6rxwcse2ksfheg2r8q26htqf7eh75ecs70njdna56s8rn4vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUFJSZksySUhwcktwSUZI
            WFN6K21LcWwyNnRLMllIRkdiYWIyRkpPNFh3CmN6K1c0b0NQckpHdSs5dXZSV2RW
            eEFMZUhWTFJrQlFJSlF0cll6WDU3Z00KLS0tIEk1enBzakRmNURXcFZ6TGNRU0o5
            bmUySitPL2MwRGVRemsvM2c1aGNUS2MKn5F41ZmXI+4cgcOuG7725VBS7k3FEBCc
            EQ8n66auZnIn9hF1OthsFhPHLLx4+oz7wtKsnycwq2eT7leUyaO7MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T10:24:13Z"
    mac: ENC[AES256_GCM,data:f2RA+4lTYxp7yzJ61nal+rR3J7X/kf3obKx2nKiriTsNyloKtuRIlwYPowts3F/jzQNb4P2S3WNyOm43qf4BrCLE2YwxttaawCXn6+XiSoeYyT7obj2k572UTvsFgoSCftoFwThntbY00napgAtXSft+ZgijdX6+DshdorMk7gM=,iv:VvK8YZt1jtlIWWKIoo99nJmyE5ibS4Vf0ZC0mRKyyOA=,tag:GRcDXbfnHOdEjbPoM4MLBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
