apiVersion: ENC[AES256_GCM,data:Lbc=,iv:J/oryvp4mKt1N0PooCPY8Nr4cHG2plWuiLaaSsxZJ80=,tag:s7NqDZdFeWZaFkOCvLiAwg==,type:str]
kind: ENC[AES256_GCM,data:gNbLpss1,iv:E0I6WMWek1wR19wWn9j7hhY76c8ZrjB7j84egqmu4Rs=,tag:LeNceVfY5vUnL70jK9R7+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HrY4sg1Xi9d3pNnMtEZq,iv:AXiLUeARA7lt5uQRKdfa3M+mt4wY55AJOrg/5BxbyCA=,tag:fZikMl255oFo1VrG/yBPWg==,type:str]
    namespace: ENC[AES256_GCM,data:vBg3ceCBRgaU5A==,iv:cS77w/VN3eRsxqBBeTEqQQ15ntaGjaWHiFHoaEArZko=,tag:gAX0+N3TnV8C/B/SZMYNjw==,type:str]
type: ENC[AES256_GCM,data:MSawX+RU,iv:QVqSyor5643KY9O4YN4V1Cxs/lkq/XLeN9+sZYGpChM=,tag:X4zVDI6H3zDknFDnRC+X5A==,type:str]
data: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgfw7y6cwv6rxwcse2ksfheg2r8q26htqf7eh75ecs70njdna56s8rn4vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY1JSMmNXYmFoN1pES09I
            T1NIVFBiTWdrNnRWaWs5Q0s5c1I1aSsreWpvCkM2eXRUeW5aUlg5RHZya1JYeFNv
            OW41NC85eWZFek5PdXF6WnFFQTN0OHcKLS0tIEZkSytFaGlqZG1TY0JlMEVZc3cy
            bE95R1Q3U0xDc3VBZDR1N05UdjRCWVUKSvIhmfxyF1zOFxU3Y0lT8KzrvZKPERqz
            yUuCIXiRSimyL1/xnVijyzkNFisYsxH6wBrFGVfBM3+Y1JYZTiEPDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T10:24:13Z"
    mac: ENC[AES256_GCM,data:SXzpVdqDZFA9jHVY+69ud5dhcJia4x54VoGpIqkVRAwlNPAifDHx6XcetuT57v+QM2g1AWOk4wU3BUCYDik27LqazbWM2fcqX1yf3VqNiXzdU25PV+mGoPZx4/WkZS86I4+Bx4AWQ/ZzI2Utae0enwNhWVCxWeucQfwZko/S/Ps=,iv:T7EXCVBaP0F+mg74aTiUdwuEHU+izw5yNhk9EyV0Sow=,tag:DXRSljAMpox35Zyg2UMwJA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
